// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace _360Generator.Templates.Frontend.Data
{
    using _360Generator.Metadata;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class PortalDataProviderTemplate : PortalDataProviderTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"import { BaseDataProvider } from 'App/Base/BaseDataProvider';
import { Constants } from 'App/Base/Constants';
import { DataProviderCallOptions } from 'App/Base/Data/DataProviderCallOptions';
import { DataProviderExecuteOptions } from 'App/Base/Data/DataProviderExecuteOptions';
import { DateHelper } from ""App/Base/Helpers/DateHelper"";
import { ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataService } from \'App/");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module.ModuleName));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("/Data/");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataService\';\nimport { ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write(" } from \'App/");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module.ModuleName));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("/Model/");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("\';\nimport * as _ from \'underscore\';\nimport { ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module.ModuleName));
            
            #line default
            #line hidden
            this.Write("Constants } from \'App/");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module.ModuleName));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module.ModuleName));
            
            #line default
            #line hidden
            this.Write("Constants\';\nimport { UserInfo } from \'App/Base/Framework/UserInfo\';\n\nexport class" +
                    " ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataProvider extends BaseDataProvider {\n    public static getDataSource(");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write("List: Array<");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write(">): kendo.data.DataSource {\n        var dataSourceOptions: kendo.data.DataSourceO" +
                    "ptions = {};\n\n        dataSourceOptions.schema = {};\n\n        dataSourceOptions." +
                    "data = ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write("List;\n\n        dataSourceOptions.pageSize = Constants.defaultPageSize;\n\n        d" +
                    "ataSourceOptions.schema.model = ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataProvider.getKendoModel();\n        dataSourceOptions.schema.parse = (data: any" +
                    "): any => {\n            return ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write(@"DataProvider.preParseResponse(data);
        };

        var dataSource: kendo.data.DataSource = new kendo.data.DataSource(dataSourceOptions);

        return dataSource;
    }

    public static getList(callOptions: DataProviderCallOptions): kendo.data.DataSource {
        callOptions.dataModel = ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataProvider.getKendoModel();\n\n        callOptions.preParseResponse = (data: any)" +
                    ": any => {\n            return ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataProvider.preParseResponse(data);\n        };\n\n        return ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataService.getInstance().getList(\n            callOptions);\n    }\n\n    public st" +
                    "atic getLookupListExecuted(executeOptions: DataProviderExecuteOptions): void {\n " +
                    "       ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataService.getInstance().getLookupListExecuted(\n            executeOptions);\n   " +
                    " }\n\n    public static refresh(executeOptions: DataProviderExecuteOptions): JQuer" +
                    "yPromise<any> {\n        return ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataService.getInstance().refresh(executeOptions);\n    }\n\n    public static getLo" +
                    "okupList(callOptions: DataProviderCallOptions, isAggregated: boolean): kendo.dat" +
                    "a.DataSource {\n        callOptions.dataModel = ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataProvider.getKendoModel();\n\n        callOptions.preParseResponse = (data: any)" +
                    ": any => {\n            return ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataProvider.preParseResponse(data);\n        };\n\n        return ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataService.getInstance().getLookupList(\n            callOptions, isAggregated);\n" +
                    "    }\n");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
if (screens.Contains(Entity.screenEnum.Get)){
            
            #line default
            #line hidden
            this.Write("  \n\n    public static getDetailAsync(executeOptions: DataProviderExecuteOptions, " +
                    "");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write("Id: string): Promise<");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("> {\n        executeOptions.preParseExecute = (");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("): ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write(" => {\n            return ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataProvider.preParseExecute(");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(");\n        };\n\n        var promise = new Promise<");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write(">((resolve, reject) => {\n            executeOptions.callback = (");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("): void => {\n                resolve(");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(");\n            }\n        });\n\n        ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataService.getInstance().getDetail(\n            executeOptions,\n            ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write("Id);\n\n        return promise;\n    }\n\n\n    public static getDetail(executeOptions:" +
                    " DataProviderExecuteOptions, ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write("Id: string): void {\n        executeOptions.preParseExecute = (");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("): ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write(" => {\n            return ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataProvider.preParseExecute(");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(");\n        };\n\n        ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataService.getInstance().getDetail(\n            executeOptions,\n            ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write("Id);\n    }\n");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\n");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
if (screens.Contains(Entity.screenEnum.Post)){
            
            #line default
            #line hidden
            this.Write("  \n\n    public static create(executeOptions: DataProviderExecuteOptions,\n        " +
                    "");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("): void {\n        ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(".companyContext = executeOptions.companyContext;\n\n        ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataService.getInstance().create(\n            executeOptions,\n            ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(");\n    }\n");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("\n\n");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
if (screens.Contains(Entity.screenEnum.Put)){
            
            #line default
            #line hidden
            this.Write("  \n\n    public static update(executeOptions: DataProviderExecuteOptions,\n        " +
                    "");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("): void {\n        ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(".companyContext = executeOptions.companyContext;\n\n        ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataService.getInstance().update(\n            executeOptions,\n            ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(");\n    }\n");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("\n    private static getKendoModel(): typeof kendo.data.Model {\n        var fields" +
                    ": any = ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write(@"DataProvider.getFields();

        var model: typeof kendo.data.Model = kendo.data.Model.define({
            fields: fields
        });

        return model;
    }

    private static getFields(): any {
        return {
            refreshedOn: { type: 'date' },
            ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(@"Id: { type: 'string' },
            name: { type: 'string' },
            description: { type: 'string' },
            companyContext: { type: 'string' },
            createdOn: { type: 'date' }
        };
    }

    private static preParseResponse(data: any): any {
        var ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write("List: Array<");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("> = data.result;\n\n        if (data.result === void 0) {\n            ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write("List = data;\n        }\n\n        _.each<");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write("List, (");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("): void => {\n            ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataProvider.preParseExecute(");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(");\n        });\n\n        return data;\n    }\n\n    protected static preParseExecute(" +
                    "");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("): ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write(" {\n        if (");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write("Id.length === 0) {\n            ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write("Id = null;\n        }\n\n        ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(".createdOn = DateHelper.fromUtcDateTime(BaseDataProvider.parseDate(");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(".createdOn));\n\n        switch (");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(".package.packageCode) {\n            case ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module.ModuleName));
            
            #line default
            #line hidden
            this.Write("Constants.profileEntryPackageCode:\n                ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(".package.packageDisplayName = ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module.ModuleName));
            
            #line default
            #line hidden
            this.Write("Constants.entryPackageName;\n                break;\n            case ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module.ModuleName));
            
            #line default
            #line hidden
            this.Write("Constants.profileBusinessPackageCode:\n                ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(".package.packageDisplayName = ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module.ModuleName));
            
            #line default
            #line hidden
            this.Write("Constants.businessPackageName;\n                break;\n            default:\n      " +
                    "          break;\n        }\n\n        ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(".companyName = UserInfo.getCompanyName(");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(".companyContext);\n\n        return ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write(";\n    }\n\n    private static getKendoTreeListModel(): typeof kendo.data.TreeListMo" +
                    "del {\n        var fields: any = ");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("DataProvider.getFields();\n\n        var model: typeof kendo.data.TreeListModel = k" +
                    "endo.data.TreeListModel.define({\n            id: \'");
            
            #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LowerInitial(entity)));
            
            #line default
            #line hidden
            this.Write("Id\',\n            fields: fields,\n            expanded: true\n        });\n\n        " +
                    "return model;\n    }\n}\n\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"

 private string LowerInitial(string name)
 { return name[0].ToString().ToLowerInvariant() + name.Substring(1);}

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\HP\source\repos\Repo1\P360Code_generator\Templates\Frontend\Data\PortalDataProviderTemplate.tt"

private global::_360Generator.Metadata.Module _moduleField;

/// <summary>
/// Access the module parameter of the template.
/// </summary>
private global::_360Generator.Metadata.Module module
{
    get
    {
        return this._moduleField;
    }
}

private string _entityField;

/// <summary>
/// Access the entity parameter of the template.
/// </summary>
private string entity
{
    get
    {
        return this._entityField;
    }
}

private global::System.Collections.Generic.List<_360Generator.Metadata.Entity.screenEnum> _screensField;

/// <summary>
/// Access the screens parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<_360Generator.Metadata.Entity.screenEnum> screens
{
    get
    {
        return this._screensField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool moduleValueAcquired = false;
if (this.Session.ContainsKey("module"))
{
    this._moduleField = ((global::_360Generator.Metadata.Module)(this.Session["module"]));
    moduleValueAcquired = true;
}
if ((moduleValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("module");
    if ((data != null))
    {
        this._moduleField = ((global::_360Generator.Metadata.Module)(data));
    }
}
bool entityValueAcquired = false;
if (this.Session.ContainsKey("entity"))
{
    this._entityField = ((string)(this.Session["entity"]));
    entityValueAcquired = true;
}
if ((entityValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("entity");
    if ((data != null))
    {
        this._entityField = ((string)(data));
    }
}
bool screensValueAcquired = false;
if (this.Session.ContainsKey("screens"))
{
    this._screensField = ((global::System.Collections.Generic.List<_360Generator.Metadata.Entity.screenEnum>)(this.Session["screens"]));
    screensValueAcquired = true;
}
if ((screensValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("screens");
    if ((data != null))
    {
        this._screensField = ((global::System.Collections.Generic.List<_360Generator.Metadata.Entity.screenEnum>)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class PortalDataProviderTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
